version: '2'
services:
    db: 
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: app
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3307:3306"
        volumes:
            -   "./mysql:/var/lib/mysql"
    app: 
        build: .
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        volumes: 
            - ".:/app"
        ports: 
            - "3001:3000"
        depends_on:
            - db
            - elasticsearch
        links:
            - db
        environment:
            DB_USER: root
            DB_NAME: app
            DB_PASSWORD: password
            DB_HOST: db
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3
        environment:
            - cluster.name=chat-system-cluster
            - node.name=chat-system-node
            - bootstrap.memory_lock=true
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
            - xpack.security.enabled=false
            - xpack.monitoring.enabled=false
            - xpack.graph.enabled=false
            - xpack.watcher.enabled=false
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - "./elasticsearch:/usr/share/elasticsearch/data"
        ports:
            - "9200:9200"
            - "9300:9300"